### ISSUE TITLE
Minor Typo

### ISSUE THREAD

**Issue by DanagaMoose** [c3d/elfe#1]
ELIoT derives from XLR. It is a specially trimmed-down version that does not require LLVM and can work in full interpreted mode, making it easier to compiler and use, but also safer, since you cannot call arbitrary C functions.

Should probably use compile and not compiler

ELIoT derives from XLR. It is a specially trimmed-down version that does not require LLVM and can work in full interpreted mode, making it easier to compile and use, but also safer, since you cannot call arbitrary C functions.

**Comment by c3d** [comment]
Thanks. Fixed.

**Comment by DanagaMoose** [comment]
And such quick turnaround!

I am really looking forward to playing around with this.
